services:
  muthur:
    build:
      context: .
      dockerfile: Dockerfile
    image: alien-muthur:latest
    container_name: alien-muthur
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
